### ISSUE TITLE
您好，有点问题需要您帮忙

### ISSUE THREAD

**Issue by wangDong524** [HorieYuan/TransformerTextSummarization#1]
1.我在训练的时候日志输出是这样的，是不是有问题呀
epoch 41, loss 8.219, best_loss 8.219, best_epoch 41
['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
epoch 42, batch 0, batch_loss 8.261
['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]']
epoch 42, loss 8.192, best_loss 8.192, best_epoch 42
['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
2.按照您hyper_parameters.py文件中的参数训练大概要多长时间呀

**Comment by jappre** [comment]
我的日志也是这样的，运行summarize.py 只能打印出模型的编号。

**Comment by HorieYuan** [comment]
@wangDong524 @jappre 我训练数据是lcsts，一共有2081173条，忘了多久有效果的，一个epoch差不多5个小时，一开始输出'[SEP]'正常。

**Comment by cedar33** [comment]
> 1.我在训练的时候日志输出是这样的，是不是有问题呀
> epoch 41, loss 8.219, best_loss 8.219, best_epoch 41
> ['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
> epoch 42, batch 0, batch_loss 8.261
> ['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
> ['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
> ['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]']
> epoch 42, loss 8.192, best_loss 8.192, best_epoch 42
> ['[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
> 2.按照您hyper_parameters.py文件中的参数训练大概要多长时间呀

41个epoch还是这样啊，后来解决了吗？

**Comment by bubbleqi** [comment]
你好，请问data中的vocab.pkl有吗

**Comment by HorieYuan** [comment]
> 你好，请问data中的vocab.pkl有吗

训练时自动生成的，可以把这一行取消注释https://github.com/HorieYuan/TransformerTextSummarization/blob/a69c6b25a2f54822b08ec1d9754c21b1a2ad94ad/code/train.py#L122

**Comment by crownzcq** [comment]
> @wangDong524 @jappre 我训练数据是lcsts，一共有2081173条，忘了多久有效果的，一个epoch差不多5个小时，一开始输出'[SEP]'正常。
LCSTS总训练数据是2400591条，请问您是进行筛选了吗？根据什么样的规则进行筛选的？

**Comment by Neverkuse** [comment]
File "C:\Users\Yukai Chen\anaconda3\envs\tensorflow\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
这个问题怎么解决？

**Comment by chfnb** [comment]
我想问一下，最后summarize输出的是['CLS']字符串，表示什么意思？

**Comment by bubbleqi** [comment]
[CLS]就是classification的意思，可以理解为用于下游的分类任务。网上搜一搜？就是一个符号






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chfnb"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 晚上8:10
收件人: "HorieYuan/TransformerTextSummarization"<TransformerTextSummarization@noreply.github.com&gt;; 
抄送: "396988352"<396988352@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1)





 
我想问一下，最后summarize输出的是['CLS']字符串，表示什么意思？

**Comment by chfnb** [comment]
> [CLS]就是classification的意思，可以理解为用于下游的分类任务。网上搜一搜？就是一个符号
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chfnb"<notifications@github.com&gt;; 发送时间: 2020年11月19日(星期四) 晚上8:10 收件人: "HorieYuan/TransformerTextSummarization"<TransformerTextSummarization@noreply.github.com&gt;; 抄送: "396988352"<396988352@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 我想问一下，最后summarize输出的是['CLS']字符串，表示什么意思？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哦哦，但这个输出对于摘要的生成有什么指示吗？我要怎样通过输入一篇文章得到它的摘要？谢谢

**Comment by change0929** [comment]
> 我的日志也是这样的，运行summarize.py只能打印出模型的编号。

我也是运行summarize.py只能打印出模型的编号，请问您解决了吗

**Comment by chfnb** [comment]
您好，不好意思，我还没有解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 晚上7:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1)





  
我的日志也是这样的，运行summarize.py只能打印出模型的编号。
  
我也是运行summarize.py只能打印出模型的编号，请问您解决了吗

**Comment by change0929** [comment]
> 您好，不好意思，我还没有解决
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:29 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 我的日志也是这样的，运行summarize.py只能打印出模型的编号。 我也是运行summarize.py只能打印出模型的编号，请问您解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
您也是运行summarize.py只能打印出模型的编号？是不是单词表有问题啊

**Comment by chfnb** [comment]
您好，我印象中是运行summarize.py打印出SEQ这类的东西。具体是什么原因我没什么印象了。这是我去年为了完成作业而查的代码，现在已经没什么印象了，不好意思。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 晚上7:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1)





  
您好，不好意思，我还没有解决
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:29 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 我的日志也是这样的，运行summarize.py只能打印出模型的编号。 我也是运行summarize.py只能打印出模型的编号，请问您解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
 您也是运行summarize.py只能打印出模型的编号？是不是单词表有问题啊

**Comment by change0929** [comment]
> 您好，我印象中是运行summarize.py打印出SEQ这类的东西。具体是什么原因我没什么印象了。这是我去年为了完成作业而查的代码，现在已经没什么印象了，不好意思。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 您好，不好意思，我还没有解决 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:29 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 我的日志也是这样的，运行summarize.py只能打印出模型的编号。 我也是运行summarize.py只能打印出模型的编号，请问您解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您也是运行summarize.py只能打印出模型的编号？是不是单词表有问题啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, o

> 您好，我印象中是运行summarize.py打印出SEQ这类的东西。具体是什么原因我没什么印象了。这是我去年为了完成作业而查的代码，现在已经没什么印象了，不好意思。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 您好，不好意思，我还没有解决 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年3月29日(星期一) 晚上7:29 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HorieYuan/TransformerTextSummarization] 您好，有点问题需要您帮忙 (#1) 我的日志也是这样的，运行summarize.py只能打印出模型的编号。 我也是运行summarize.py只能打印出模型的编号，请问您解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 您也是运行summarize.py只能打印出模型的编号？是不是单词表有问题啊 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好吧谢谢

**Comment by change0929** [comment]
> > @wangDong524 @jappre 我训练数据是lcsts，一共有2081173条，忘了多久有效果的，一个epoch差不多5个小时，一开始输出'[SEP]'正常。
> > LCSTS总训练数据是2400591条，请问您是进行筛选了吗？根据什么样的规则进行筛选的？
您好，请问LCSTS训练集是直接拿来用吗，为什么会有条错误数据，应该要与处理一下吧？

**Comment by change0929** [comment]
您好，LCSTS数据集拿来怎么预处理成要求的格式啊

**Comment by mlm22222** [comment]
Traceback (most recent call last):
  File "D:/TransformerTextSummarization-master/code/train.py", line 135, in <module>
    main(TRAIN_DATA_PATH)
  File "D:/TransformerTextSummarization-master/code/train.py", line 131, in main
    train(transformer, dataloader, LR, N_EPOCHS, vocab, CTX)
  File "D:/TransformerTextSummarization-master/code/train.py", line 78, in train
    gpu_Xs = gutils.split_and_load(X, ctx, even_split=False)
  File "C:\Anaconda3\envs\tensor\lib\site-packages\mxnet\gluon\utils.py", line 110, in split_and_load
    if len(ctx_list) == 1:
TypeError: object of type 'Context' has no len()


大佬，问一下，这是什么情况，求教
if len(ctx_list) == 1:
TypeError: object of type 'Context' has no len()

**Comment by zhouyongxiang** [comment]
> 您好，LCSTS数据集拿来怎么预处理成要求的格式啊
您好大佬，这个问题你解决了吗？
