### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by fangxiang00** [HorieYuan/TransformerTextSummarization#2]
您好：
    运行train.py出现错误
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(TRAIN_DATA_PATH)
  File "train.py", line 129, in main
    train(transformer, dataloader, LR, N_EPOCHS, vocab, CTX)
  File "train.py", line 77, in train
    gpu_Xs = gutils.split_and_load(X, ctx, even_split=False)
  File "/root/anaconda3/lib/python3.7/site-packages/mxnet/gluon/utils.py", line 126, in split_and_load
    slices = split_data(data, len(ctx_list), batch_axis, even_split)
  File "/root/anaconda3/lib/python3.7/site-packages/mxnet/gluon/utils.py", line 73, in split_data
    step = size // num_slice
ZeroDivisionError: integer division or modulo by zero
看了半天没找到问题，是否是库版本的 问题

**Comment by fangxiang00** [comment]
发现问题是自己装的mxnet是非gpu版本~，请问怎么将代码改成非gpu版本~

**Comment by pulsardu** [comment]
> 发现问题是自己装的mxnet是非gpu版本~，请问怎么将代码改成非gpu版本~

想问问这个问题解决了吗
