### ISSUE TITLE
找不到训练资源

### ISSUE THREAD

**Issue by xafasddsf** [HorieYuan/TransformerTextSummarization#4]
![image](https://user-images.githubusercontent.com/53801094/108289629-b12fd800-71c9-11eb-89e2-717384bb2a08.png)
您好，我按照您的md文档，直接运行train文件，但是运行出错，显示找不到文件：
FileNotFoundError: [Errno 2] No such file or directory: '../data/train_data.tsv'
看了一个项目结构，发现data目录下确实没有train_data.tsv。请问要怎么获取train_data.tsv呢？？

**Comment by change0929** [comment]
> ![image](https://user-images.githubusercontent.com/53801094/108289629-b12fd800-71c9-11eb-89e2-717384bb2a08.png)
> 您好，我按照您的md文档，直接运行train文件，但是运行出错，显示找不到文件：
> FileNotFoundError: [Errno 2] No such file or directory: '../data/train_data.tsv'
> 看了一个项目结构，发现data目录下确实没有train_data.tsv。请问要怎么获取train_data.tsv呢？？

您好，请问您现在跑通了吗

**Comment by bluebluer** [comment]
得改成train_sample.tsv吧，但是改了以后还是报错了
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(TRAIN_DATA_PATH)
  File "train.py", line 129, in main
    train(transformer, dataloader, LR, N_EPOCHS, vocab, CTX)
  File "train.py", line 77, in train
    gpu_Xs = gutils.split_and_load(X, ctx, even_split=False)
  File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/utils.py", line 118, in split_and_load
    slices = split_data(data, len(ctx_list), batch_axis, even_split)
  File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/utils.py", line 72, in split_data
    n_each_section, extras = divmod(size, num_slice)
ZeroDivisionError: integer division or modulo by zero

**Comment by ZZUPeanut** [comment]
> 

请问这个问题解决了吗，我也是遇到同样的报错

**Comment by ZZUPeanut** [comment]
> 得改成train_sample.tsv吧，但是改了以后还是报错了 Traceback (most recent call last): File "train.py", line 133, in main(TRAIN_DATA_PATH) File "train.py", line 129, in main train(transformer, dataloader, LR, N_EPOCHS, vocab, CTX) File "train.py", line 77, in train gpu_Xs = gutils.split_and_load(X, ctx, even_split=False) File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/utils.py", line 118, in split_and_load slices = split_data(data, len(ctx_list), batch_axis, even_split) File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/utils.py", line 72, in split_data n_each_section, extras = divmod(size, num_slice) ZeroDivisionError: integer division or modulo by zero

请问这个问题解决了吗，我这边也是同样的报错

**Comment by imnunlp** [comment]
把data里面的train_sample.tsv改成train_data.tsv就可以啦
